export const FORMULARIO_PROYECTO = 'FORMULARIO_PROYECTO';
export const OBTENER_PROYECTOS = 'OBTENER_PROYECTOS';
export const AGREGAR_PROYECTO = 'AGREGAR_PROYECTO';
export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';
export const PROYECTO_ACTUAL = 'PROYECTO_ACTUAL';
export const ELIMINAR_PROYECTO = 'ELIMINAR_PROYECTO';

export const TAREAS_PROYECTOS = 'TAREAS_PROYECTOS';
export const AGREGAR_TAREAS = 'AGREGAR_TAREAS'
export const VALIDAR_TAREA = 'VALIDAR_TAREA'
export const ELIMINAR_TAREA = 'ELIMINAR_TAREA'

